### ISSUE TITLE
Suggestion - A way for offline players to stay logged in for one hour

### ISSUE THREAD

**Issue by RemiRiu95** [TheKinrar/Papyrus#11]
Some players (((me))) sometimes and for some reasons needs to disconnect multiple times in a row, for testing or just because they crashes. It would be nice to have an option for them to remain connected, using their ip address ofc.

**Comment by TheKinrar** [comment]
Related to #12, both to be implemented at the same time.
Modified title as this will only apply to offline players.
Also important to know that this would allow someone on same network (e.g home network) than another player to login with their identity
