### ISSUE TITLE
Command block - Range values 1 less

### ISSUE THREAD

**Issue by RemiRiu95** [TheKinrar/Papyrus#17]
My ranging command blocks with the most often @a[r=3] needs to be rewritten in @a[r=4] in order to catch the plate actionner. However, instead of rewriting every command blocks, can you increase the range from 1 in your concerned function ?

**Comment by TheKinrar** [comment]
you probably meant `@a[r=3]`, I guess

**Comment by RemiRiu95** [comment]
Yup but I've been corrected, regardless of my will
