### ISSUE TITLE
Commands / Command blocks - Requires lowercased commands

### ISSUE THREAD

**Issue by RemiRiu95** [TheKinrar/Papyrus#18]
On my server, a few 1.7 command blocks might contain some capital letters and it obviously breaks the command and the associated autocompletion.

Is it feasible to make them work as it was ?

**Comment by TheKinrar** [comment]
So your plugin commands are defined with lowercased names but you're using them with mixed case?

**Comment by TheKinrar** [comment]
Can't reproduce, I can run a command with the label cased in any manner and autocompletion works too.

**Comment by TheKinrar** [comment]
Which is coherent with `SimpleCommandMap` code (labels are turned into lower case before comparison):
```java
knownCommands.get(name.toLowerCase(java.util.Locale.ENGLISH));
```

**Comment by TheKinrar** [comment]
Okay, can reproduce. Only happens with command blocks, not with players.
