### ISSUE TITLE
New Material helpers

### ISSUE THREAD

**Issue by TheKinrar** [TheKinrar/Papyrus#6]
-> isArmorPiece() or isArmor()
-> isHelmet()
-> isChestplate()
-> isLeggings()
-> isBoots()
-> isSword()
-> isAxe()
-> isHoe()
-> isPickaxe()
-> isShovel()

as requested by @RemiRiu95 in c1589ef

**Comment by RemiRiu95** [comment]
isPotion() { POTION - SPLASH_POTION - LINGERING_POTION }

**Comment by TheKinrar** [comment]
?
