### ISSUE TITLE
Suggestion - Option to disable login

### ISSUE THREAD

**Issue by RemiRiu95** [TheKinrar/Papyrus#7]
Development servers should have an option to disable the login verification on player join, in order to gain some precious seconds. Ideally, in papyrus.yml.

**Comment by TheKinrar** [comment]
What are the pros of this over disabling hybrid mode and using standard offline mode?

**Comment by RemiRiu95** [comment]
Simulate the very same behaviour of the prod server on a dev server except the typing password waste of time

**Comment by TheKinrar** [comment]
Fixed in 7dacfd1
